/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/ARMCHAIR.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Armchair(props) {
  const { nodes, materials } = useGLTF('models/ARMCHAIR.glb')
  return (
    <group {...props} dispose={null} scale={props.customScale} rotation={props.customRotation}>
      <mesh geometry={nodes.ALMOFADINHAS.geometry} material={materials['Fabric Upholstery 001a']} position={[0.231, 0.608, 0.048]} rotation={[0, -0.713, 0]} />
      <mesh geometry={nodes.ALMOFADINHAS001.geometry} material={materials['Fabric Upholstery 001a']} position={[0.043, 0.554, 0.044]} rotation={[0, -0.713, 0]} />
      <mesh geometry={nodes.ASSENTO_SOLTO.geometry} material={materials['Fabric Upholstery 001a']} position={[0.027, 0, 0.025]} rotation={[0, -0.014, 0]} />
      <mesh geometry={nodes.BASE_FIXA.geometry} material={materials['Fabric Upholstery 001a']} position={[0.032, 0, 0.025]} rotation={[0, -0.014, 0]} />
      <mesh geometry={nodes.BRAÇAS.geometry} material={materials['Fabric Upholstery 001a']} position={[0.027, 0, 0.025]} rotation={[0, -0.014, 0]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Fabric Upholstery 001a']} position={[0.03, 0.678, -0.177]} rotation={[0.069, -0.014, 0.001]} />
      <mesh geometry={nodes.ENCOSTO_FIXO.geometry} material={materials['Fabric Upholstery 001a']} position={[0.032, 0.45, -0.313]} rotation={[0, -0.014, 0]} scale={[0.3, 0.05, 0.3]} />
      <mesh geometry={nodes.MADEIRA_BASE.geometry} material={materials['MADEIRA BASE']} position={[0.027, 0, 0.025]} rotation={[0, -0.014, 0]} />
      <mesh geometry={nodes.PÉS.geometry} material={materials['MADEIRA PES']} position={[0.027, 0, 0.025]} rotation={[0, -0.014, 0]} />
    </group>
  )
}

useGLTF.preload('models/ARMCHAIR.glb')
