/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/Armchair1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Armchair1(props) {
  const group = useRef()

  const { nodes, materials } = useGLTF('models/Armchair1.glb')
  console.log(nodes);
  return (
    <group {...props} dispose={null} scale={props.customScale} rotation={props.customRotation}>
      <mesh geometry={nodes.ALMOFADINHAS002.geometry} material={materials['Fabric Upholstery 001a.001']}    position={[0.231, 0.608, 0.048]} rotation={[0, -0.713, 0]} />
      <mesh geometry={nodes.ALMOFADINHAS003.geometry} material={materials['Fabric Upholstery 001a.001']} position={[0.043, 0.554, 0.044]} rotation={[0, -0.713, 0]} />
      <mesh geometry={nodes.ASSENTO_SOLTO001.geometry} material={materials['Fabric Upholstery 001a.001']} position={[0.027, 0, 0.025]} rotation={[0, -0.014, 0]} />
      <mesh geometry={nodes.BASE_FIXA001.geometry} material={materials['Fabric Upholstery 001a.001']} position={[0.032, 0, 0.025]} rotation={[0, -0.014, 0]} />
      <mesh geometry={nodes.BRAÇAS001.geometry} material={materials['Fabric Upholstery 001a.001']} position={[0.027, 0, 0.025]} rotation={[0, -0.014, 0]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Fabric Upholstery 001a.001']} position={[0.03, 0.678, -0.177]} rotation={[0.069, -0.014, 0.001]} />
      <mesh geometry={nodes.ENCOSTO_FIXO001.geometry} material={materials['Fabric Upholstery 001a.001']} position={[0.032, 0.45, -0.313]} rotation={[0, -0.014, 0]} scale={[0.3, 0.05, 0.3]} />
      <mesh geometry={nodes.MADEIRA_BASE001.geometry} material={materials['MADEIRA BASE.001']} position={[0.027, 0, 0.025]} rotation={[0, -0.014, 0]} />
      <mesh geometry={nodes.PÉS001.geometry} material={materials['MADEIRA PES.001']} position={[0.027, 0, 0.025]} rotation={[0, -0.014, 0]} />
    </group>
  )
}

useGLTF.preload('models/Armchair1.glb')
