/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/FairView.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function FairView(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('models/FairView.glb')
  return (
    <group group {...props} dispose={null} scale={props.customScale} rotation={props.customRotation}>
      <mesh geometry={nodes.Seat.geometry} material={materials.SEAT} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Seat_lower.geometry} material={materials.seat_lower} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Frame.geometry} material={materials.fram} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      {/* <mesh geometry={nodes.Stand.geometry} material={materials.paya} rotation={[Math.PI / 2, 0, 0]} scale={0.01} /> */}
      {/* <mesh geometry={nodes.Screw.geometry} material={materials.screw} rotation={[Math.PI / 2, 0, 0]} scale={0.01} /> */}
    </group>
  )
}

useGLTF.preload('models/FairView.glb')
