/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/grayChairglb.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function GrayChair(props) {
  const { nodes, materials } = useGLTF('models/grayChairglb.glb')
  return (
    <group group {...props} dispose={null} scale={props.customScale} rotation={props.customRotation}>
      <group scale={0.001}>
        <group position={[-1.163, -2.874, -9.396]}>
          <mesh geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} />
          <mesh geometry={nodes.Plane003.geometry} material={nodes.Plane003.material} />
          <mesh geometry={nodes.Box001.geometry} material={nodes.Box001.material} />
          <mesh geometry={nodes.Box002.geometry} material={nodes.Box002.material} />
          <mesh geometry={nodes.Plane004.geometry} material={nodes.Plane004.material} />
          <mesh geometry={nodes.Plane006.geometry} material={nodes.Plane006.material} />
          <mesh geometry={nodes.Plane008.geometry} material={nodes.Plane008.material} />
          <mesh geometry={nodes.Plane009.geometry} material={nodes.Plane009.material} />
          <mesh geometry={nodes.Plane010.geometry} material={nodes.Plane010.material} />
          <mesh geometry={nodes.Shape001.geometry} material={nodes.Shape001.material} />
          <mesh geometry={nodes.Shape002.geometry} material={nodes.Shape002.material} />
          <mesh geometry={nodes.Shape003.geometry} material={nodes.Shape003.material} />
        </group>
      </group>
      <PerspectiveCamera makeDefault={false} far={225.478} near={162.853} fov={39.598} position={[-144.576, 40.06, 128.834]} rotation={[-0.209, -0.847, -0.158]} />
    </group>
  )
}

useGLTF.preload('models/grayChairglb.glb')
