/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/Ottoman.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Ottoman(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('models/Ottoman.glb')
  return (
    <group ref={group} {...props} dispose={null} scale={props.customScale}>
      <group position={[0, 0.59, 0]} scale={0.105}>
        <mesh geometry={nodes.Ottoman_legs.geometry} material={materials['Ottoman wood']} position={[0, -4.408, 0]} scale={15.615} />
        <mesh geometry={nodes.Ottoman_seams.geometry} material={materials['Ottoman fabric']} position={[0, -3.695, 0]} rotation={[0, Math.PI / 4, 0]} scale={16.901} />
        <mesh geometry={nodes.Ottoman_seat.geometry} material={materials['Ottoman fabric']} position={[0, -3.695, 0]} scale={16.901} />
        <mesh geometry={nodes.Ottoman_seat_cushion.geometry} material={materials['Ottoman fabric']} position={[0, -3.695, 0]} scale={[2.518, 2.432, 2.518]} />
      </group>
    </group>
  )
}

useGLTF.preload('models/Ottoman.glb')
