/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/Red_sofa_glb.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function RedSofa(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('models/Red_sofa_glb.glb')
  return (
    <group ref={group} {...props} dispose={null}    scale={props.customScale} rotation={props.customRotation}>
      <mesh geometry={nodes.Cube_1.geometry} material={materials.DefaultMaterial} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Cube002_1.geometry} material={materials.DefaultMaterial} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Circle_1.geometry} material={materials.DefaultMaterial} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Cube003_1.geometry} material={materials.DefaultMaterial} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('models/Red_sofa_glb.glb')
